name: Create release and tag repo

on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: "Set release version (optional)"
        required: false

permissions:
  contents: write

env:
  RELEASE_VERSION: ${{ github.event.inputs.RELEASE_VERSION }}

jobs:
  build:
    name: "Create release and Github tag"
    runs-on: [self-hosted, linux, X64]
    outputs:
      VERSION_BUILD: ${{ steps.get-version.outputs.VERSION_BUILD }}     
    
    steps:
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 25

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
         maven-version: 3.9.2

    - name: checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: '0'
        
    - name: Maven release pepare
      run: | 
        git config --global user.email "code@starwit.de"
        git config --global user.name "Starwit"
        if [ ! -z "${{ env.RELEASE_VERSION }}" ]
        then
          echo "new version manually set to ${{ env.RELEASE_VERSION }}"
          mvn -B build-helper:parse-version versions:set -DnewVersion=${{ env.RELEASE_VERSION }}-SNAPSHOT versions:commit --settings .github/workflows/settings.xml --file pom.xml
        fi
        echo "mvn generate-sources --file pom.xml"
        mvn generate-sources --file pom.xml
        echo "git add ."
        git add .
        modifications=$(git status | grep "modified" || true)
        if [ ! -z "$modifications" ]
        then
          echo "modifications found: $modifications"
          git commit -m "modified changelog"
          git push
        fi
        mvn -B release:clean release:prepare -Darguments="-DskipTests" --settings .github/workflows/settings.xml --file pom.xml
        mvn -B release:clean --settings .github/workflows/settings.xml --settings .github/workflows/settings.xml --file pom.xml
      env:
         CI: false
         MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
         MAVEN_GPG_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get tag name
      run: |
        echo "TAG=$( git describe --abbrev=0 )" >> $GITHUB_ENV

    - name: Checkout tag
      run: |
        git checkout ${{ env.TAG }}

    - name: Build Java lib
      run: | 
        mvn package --settings ${{ github.workspace }}/.github/workflows/settings.xml
      env:
         CI: false
         MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
         MAVEN_GPG_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create github release
      run: gh release create ${{ env.TAG }} ./target/*.jar ./target/*.asc
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit generated code and changelog
      run: |
        git config --global user.email "code@starwit.de"
        git config --global user.name "Starwit"
        git add .
        modifications=$(git status | grep "modified" || true)
        if [ ! -z "$modifications" ]
        then
          echo "modifications found: $modifications"
          git commit -m "Bumping version to ${{ env.RELEASE_VERSION }}"
          git push
        fi
      env:
         CI: false
    

