name: Publish libraries

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

env:
  RELEASE_VERSION: ${{ github.event.inputs.RELEASE_VERSION }}

jobs:
  publish_java_lib:
    name: "Publish Java library"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 25

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
         maven-version: 3.9.2    
    
    - name: checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: '0'

    - name: get last tag
      run: |
        echo "Getting last tagged versiont"
        echo "TAG=$( git describe --abbrev=0 )" >> $GITHUB_ENV
        echo "Publishing version $TAG"

    - name: checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: '0'
        ref: ${{ env.TAG }}

    - name: check git tag
      run: git status
         
    - name: Build Maven project
      run: mvn clean -B package
      env:
         CI: false
         MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
         MAVEN_GPG_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}

    - name: Publish Maven package to Maven Central
      run: mvn deploy --settings ${{ github.workspace }}/.github/workflows/settings.xml
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        MAVEN_GPG_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}        
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}